Vagrant.configure("2") do |config|
  config.vm.define "consul1" do |c|
    c.vm.box = "ubuntu/trusty64"
    c.vm.hostname = "consul1"
    c.vm.box_check_update = false
    c.vm.network "private_network", ip: "192.168.33.11"
    c.vm.network "private_network", ip: "192.168.33.111"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get -y upgrade
      apt-get -y autoclean
      apt-get -y autoremove
	  apt-get -y install unzip
	  wget -q https://releases.hashicorp.com/consul/0.8.1/consul_0.8.1_linux_amd64.zip
	  unzip consul*.zip
    SHELL
  end
  config.vm.define "consul2" do |c|
    c.vm.box = "ubuntu/trusty64"
    c.vm.hostname = "consul2"
    c.vm.box_check_update = false
    c.vm.network "private_network", ip: "192.168.33.12"
    c.vm.network "private_network", ip: "192.168.33.112"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get -y upgrade
      apt-get -y autoclean
      apt-get -y autoremove
	  apt-get -y install unzip
	  wget -q https://releases.hashicorp.com/consul/0.8.1/consul_0.8.1_linux_amd64.zip
	  unzip consul*.zip
    SHELL
  end
  config.vm.define "consul3" do |c|
    c.vm.box = "ubuntu/trusty64"
    c.vm.hostname = "consul3"
    c.vm.box_check_update = false
    c.vm.network "private_network", ip: "192.168.33.13"
    c.vm.network "private_network", ip: "192.168.33.113"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get -y upgrade
      apt-get -y autoclean
      apt-get -y autoremove
	  apt-get -y install unzip
	  wget -q https://releases.hashicorp.com/consul/0.8.1/consul_0.8.1_linux_amd64.zip
	  unzip consul*.zip
    SHELL
  end
end
