Vagrant.configure("2") do |config|
  config.vm.define "consul1" do |c|
    c.vm.box = "ubuntu/xenial64"
    c.vm.hostname = "consul1"
    c.vm.box_check_update = false
    c.vm.network "private_network", ip: "192.168.33.11"
    c.vm.network "private_network", ip: "192.168.33.111"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get install unzip

      echo "192.168.33.11 consul1" >> /etc/hosts
      echo "192.168.33.12 consul2" >> /etc/hosts
      echo "192.168.33.13 consul3" >> /etc/hosts

      wget -q https://releases.hashicorp.com/consul/0.9.0/consul_0.9.0_linux_amd64.zip
      unzip consul*.zip
      rm *.zip
    SHELL
  end
  config.vm.define "consul2" do |c|
    c.vm.box = "ubuntu/xenial64"
    c.vm.hostname = "consul2"
    c.vm.box_check_update = false
    c.vm.network "private_network", ip: "192.168.33.12"
    c.vm.network "private_network", ip: "192.168.33.112"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get -y install unzip

      echo "192.168.33.11 consul1" >> /etc/hosts
      echo "192.168.33.12 consul2" >> /etc/hosts
      echo "192.168.33.13 consul3" >> /etc/hosts

      wget -q https://releases.hashicorp.com/consul/0.9.0/consul_0.9.0_linux_amd64.zip
      unzip consul*.zip
      rm *.zip
    SHELL
  end
  config.vm.define "consul3" do |c|
    c.vm.box = "ubuntu/xenial64"
    c.vm.hostname = "consul3"
    c.vm.box_check_update = false
    c.vm.network "private_network", ip: "192.168.33.13"
    c.vm.network "private_network", ip: "192.168.33.113"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get -y install unzip

      echo "192.168.33.11 consul1" >> /etc/hosts
      echo "192.168.33.12 consul2" >> /etc/hosts
      echo "192.168.33.13 consul3" >> /etc/hosts

      wget -q https://releases.hashicorp.com/consul/0.9.0/consul_0.9.0_linux_amd64.zip
      unzip consul*.zip
      rm *.zip
    SHELL
  end
end
